mixed-port: 7890
#---------------------------------------------------#
allow-lan: false
mode: Rule
log-level: silent
external-controller: 127.0.0.1:60000

# 节点配置文件统一存放在 ./profiles/proxies/ 目录中


## 代理集

proxy-providers:
# 从链接导入的配置文件（雨燕机场70G不限时）
#  foo:
#    type: http
#    path: ./profiles/proxies/foo.yaml
#    url: https://dy.ikuncloud.com/api/v1/client/subscribe?token=879ca61fcba1636a0f2196274cce0ce8
#    interval: 3600 
#    filter: 'Hong Kong' # 筛选出含有该关键词的节点
#    health-check:
#      enable: true
#      url: http://www.gstatic.com/generate_204
#      interval: 900

# # 从链接导入的配置文件（乘风机场50G一个月---20230519到期）
#  foo1:
#    type: http
#    path: ./profiles/proxies/foo1.yaml
#    url: https://aricke.com/api/v1/client/subscribe?token=6fae2b0731f60c14e17b27ee74abbb24
#    interval: 3600 
#    filter: 'Hong Kong' # 删选出含有该关键词的节点
#    health-check:
#      enable: true
#      url: http://www.gstatic.com/generate_204
#      interval: 900

# # 从链接导入的配置文件（高速店机场6T/月---20231019到期---速度快，但节点要少）
#  foo2:
#    type: http
#    path: ./profiles/proxies/foo2.yaml
#    url: https://liangyuandian.club/api/v1/client/subscribe?token=7d026728582965af793ecf2ee3035029
#    interval: 3600 
#    filter: 'Hong Kong' # 删选出含有该关键词的节点
#    health-check:
#      enable: true
#      url: http://www.gstatic.com/generate_204
#      interval: 900

# # 从链接导入的配置文件（nanoport机场2T/月---20231014到期）
#  foo3:
#    type: http
#    path: ./profiles/proxies/foo3.yaml
#    url: https://subv5.nanoport.xyz/api/v1/client/subscribe?token=99594d9869c11a961d983e9ce2fc933c
#    interval: 3600 
#    filter: 'Hong Kong' # 删选出含有该关键词的节点
#    health-check:
#      enable: true
#      url: http://www.gstatic.com/generate_204
#      interval: 900


# # 从链接导入的配置文件（赔钱机场100G/月---20240123到期---每日10%）
#  foo4:
#    type: http
#    path: ./profiles/proxies/foo5.yaml
#    url: https://pqjc.site/api/v1/client/subscribe?token=40f983109bcced8acf4f178e9f7b209f
#    interval: 3600 
#    filter: 'Hong Kong' # 删选出含有该关键词的节点
#    health-check:
#      enable: true
#      url: http://www.gstatic.com/generate_204
#      interval: 900

# 从链接导入的配置文件（一元机场500G/月---20230819到期）
 foo5:
   type: http
   path: ./profiles/proxies/foo6.yaml
   url: https://sub.id9.cc/sub?target=clash&new_name=true&url=https%3A%2F%2Fsub1.smallstrawberry.com%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D5a98ed18d7d9a50ec3f1b6ff68659f64&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online.ini&include=%E9%A6%99%E6%B8%AF&emoji=true&list=false&tfo=false&scv=false&fdn=false&sort=false
   interval: 3600 
   filter: '香港' # 删选出含有该关键词的节点
   health-check:
     enable: true
     url: http://www.gstatic.com/generate_204
     interval: 900

# # 从链接导入的配置文件（一日机场300G/月---20250214到期）0514前流量用完---
#  foo6:
#    type: http
#    path: ./profiles/proxies/foo4.yaml
#    url: https://sub.lianpi.xyz/api/v1/client/subscribe?token=6afb0b217414a6977f06a02b2ad76e83
#    interval: 3600 
#    filter: 'Hong Kong' # 删选出含有该关键词的节点
#    health-check:
#      enable: true
#      url: http://www.gstatic.com/generate_204
#      interval: 900

 # 从本地导入的 clash 配置文件
 # bar:
 #   type: file
 #   path: ./profiles/proxies/bar.yaml
 #   health-check:
 #     enable: true
 #     url: http://www.gstatic.com/generate_204
 #     interval: 600


## 策略组

proxy-groups:
  - name: PROXY
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 900
    use: # 引入proxy-provider 使用 use 关键字
     # - foo
     # - foo1
     # - foo2
     # - foo3
     # - foo4
     - foo5
    proxies:
     - DIRECT
  # - name: Netflix
  #   type: url-test
  #   url: http://www.gstatic.com/generate_204
  #   interval: 900
  #   use:
  #     - BLSG
  # - name: Netflix
  #   type: url-test
  #   url: http://www.gstatic.com/generate_204
  #   interval: 900
  #   use:
  #     - BLSG
  # - name: Netflix
  #   type: url-test
  #   url: http://www.gstatic.com/generate_204
  #   interval: 900
  #   use:
  #     - BLSG
  # - name: Netflix
  #   type: url-test
  #   url: http://www.gstatic.com/generate_204
  #   interval: 900
  #   use:
  #     - BLSG
  # - name: Netflix
  #   type: url-test
  #   url: http://www.gstatic.com/generate_204
  #   interval: 900
  #   use:
  #     - BLSG
  # - name: Netflix
  #   type: url-test
  #   url: http://www.gstatic.com/generate_204
  #   interval: 900
  #   use:
  #     - BLSG






## clash-rules项目提供的规则集

rule-providers:
  reject: # 广告域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./profiles/rules/reject.yaml
    interval: 86400
  icloud: # iCloud 域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./profiles/rules/icloud.yaml
    interval: 86400
  apple: # Apple 在中国大陆可直连的域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./profiles/rules/apple.yaml
    interval: 86400
  google: # Google 在中国大陆可直连的域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./profiles/rules/google.yaml
    interval: 86400
  proxy: # 代理域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./profiles/rules/proxy.yaml
    interval: 86400
  direct: # 直连域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./profiles/rules/direct.yaml
    interval: 86400
  private: # 私有网络专用域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./profiles/rules/private.yaml
    interval: 86400
  gfw:  # GFWList 域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./profiles/rules/gfw.yaml
    interval: 86400
  greatfire:  # GreatFire 域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./profiles/rules/greatfire.yaml
    interval: 86400
  tld-not-cn:  # 非中国大陆使用的顶级域名列表
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./profiles/rules/tld-not-cn.yaml
    interval: 86400
  telegramcidr:  # Telegram 使用的 IP 地址列表
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./profiles/rules/telegramcidr.yaml
    interval: 86400
  cncidr: # 中国大陆 IP 地址列表
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./profiles/rules/cncidr.yaml
    interval: 86400
  lancidr: # 局域网 IP 及保留 IP 地址列表
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./profiles/rules/lancidr.yaml
    interval: 86400


## 分流规则

rules:
  - DOMAIN-KEYWORD,orientool.top,DIRECT
  - PROCESS-NAME,v2ray,DIRECT
  - PROCESS-NAME,xray,DIRECT
  - PROCESS-NAME,naive,DIRECT
  - PROCESS-NAME,trojan,DIRECT
  - PROCESS-NAME,trojan-go,DIRECT
  - PROCESS-NAME,ss-local,DIRECT
  - PROCESS-NAME,privoxy,DIRECT
  - PROCESS-NAME,leaf,DIRECT
  - PROCESS-NAME,v2ray.exe,DIRECT
  - PROCESS-NAME,xray.exe,DIRECT
  - PROCESS-NAME,naive.exe,DIRECT
  - PROCESS-NAME,trojan.exe,DIRECT
  - PROCESS-NAME,trojan-go.exe,DIRECT
  - PROCESS-NAME,ss-local.exe,DIRECT
  - PROCESS-NAME,privoxy.exe,DIRECT
  - PROCESS-NAME,leaf.exe,DIRECT
  - PROCESS-NAME,Surge,DIRECT
  - PROCESS-NAME,Surge 2,DIRECT
  - PROCESS-NAME,Surge 3,DIRECT
  - PROCESS-NAME,Surge 4,DIRECT
  - PROCESS-NAME,Surge%202,DIRECT
  - PROCESS-NAME,Surge%203,DIRECT
  - PROCESS-NAME,Surge%204,DIRECT
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qBittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT
  - PROCESS-NAME,aria2c.exe,DIRECT
  - PROCESS-NAME,BitComet.exe,DIRECT
  - PROCESS-NAME,fdm.exe,DIRECT
  - PROCESS-NAME,NetTransport.exe,DIRECT
  - PROCESS-NAME,qbittorrent.exe,DIRECT
  - PROCESS-NAME,Thunder.exe,DIRECT
  - PROCESS-NAME,ThunderVIP.exe,DIRECT
  - PROCESS-NAME,transmission-daemon.exe,DIRECT
  - PROCESS-NAME,transmission-qt.exe,DIRECT
  - PROCESS-NAME,uTorrent.exe,DIRECT
  - PROCESS-NAME,WebTorrent.exe,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
